"""Erreurs applicatives (ADR-0007) — un cas d'usage est impossible.

Racine `ApplicationError`. Traduites à la frontière API en 404 (ressource introuvable)
ou 409 (conflit d'état) ; la couche application, elle, ignore HTTP.

**Paquet depuis l'action 2 de l'audit de maintenabilité** (03/08/2026) : les 77 classes
vivaient dans un **fichier unique de 962 lignes**, l'un des onze « passages obligés » que
l'audit a mesurés. Elles sont réparties par **thème métier** (`referentiel`, `moteur`, `tir`,
`exploitation`) et ce module les **ré-exporte toutes** : aucun import existant n'a changé,
aucune ligne de classe n'a bougé d'un caractère.
"""

from __future__ import annotations

from application.erreurs.base import ApplicationError
from application.erreurs.communs import (
    DepartCourantNonDefini,
)
from application.erreurs.exploitation import (
    AccesDejaConfigure,
    AccesNonConfigure,
    AucunDuelALancer,
    CodePosteInconnu,
    CodeScoreurInconnu,
    IdentifiantsInvalides,
    NonAuthentifie,
    PeuplementTournoiDemarre,
    PilotageSimulationInvalide,
    PosteIntrouvable,
    PosteNEstPasUnEcran,
    RattachementTournoiTermine,
    ScenarioInconnu,
    ScoreurIntrouvable,
    SessionSimulationIntrouvable,
    SimulationTournoiDemarre,
    UniteSimulationInvalide,
)
from application.erreurs.moteur import (
    ArcherDejaSorti,
    ArcherHorsBigShootOff,
    ArretIntrouvable,
    DepartIntrouvable,
    DeplacementInvalide,
    DerouleCyclique,
    EffectifSimulationInvalide,
    FormatIntrouvable,
    FormatNonSimulable,
    GabaritDuTournoiAbsent,
    InscriptionIntrouvable,
    MancheIntrouvable,
    PhaseIntrouvable,
    PhasePasDesPoules,
    PhasePasReglee,
    PhasePasUnBigShootOff,
    PhasePasUneQualification,
    PhasePasUnSuisse,
    PhasePasUnTableau,
    PhaseQualificationAbsente,
    PhaseQualificationNonSupprimable,
    PhaseSourceReferencee,
    PrelevementEnAttente,
    RencontreIntrouvable,
    ReordonnancementPhasesInvalide,
    ReplacementNonConfirme,
    TournoiIntrouvable,
    TransitionStatutInvalide,
)
from application.erreurs.referentiel import (
    BlasonHorsTournoi,
    BlasonReference,
    BriqueDejaEnBibliotheque,
    BriqueHorsBibliotheque,
    CategorieHorsTournoi,
    ChangementCategorieArcherEngage,
    ClubIntrouvable,
    ClubReference,
    DejaInscrit,
    DepartAvecInscriptions,
    DepartComplet,
    DepartEnCoursNonConfirme,
    DernierDepartNonSupprimable,
    EffectifInsuffisantPourDemarrer,
    FusionArchersEngages,
    FusionImpossible,
    GabaritIntrouvable,
    HomonymeArcher,
    InscriptionPayeeARembourser,
    NomBriqueDejaPris,
    NomClubDejaPris,
    NomFormatDejaPris,
    PhasesEngagees,
    RemboursementDejaTraite,
    RemboursementIntrouvable,
    TournoiArchiveNonModifiable,
    TournoiEnCoursNonSupprimable,
    TournoiSansDepart,
    TournoiSansPhase,
)
from application.erreurs.tir import (
    ArcherEngage,
    ArcherIntrouvable,
    BarrageIntrouvable,
    BarragePerime,
    BlasonIntrouvable,
    CategorieIntrouvable,
    DuelDesynchronise,
    EgaliteNonDepartageable,
    ForfaitDejaDeclare,
    ForfaitIntrouvable,
    ForfaitTournoiTermine,
    PhaseEnPause,
    SaisieHorsCible,
    ScoreurHorsTournoi,
    TireursDesignesInvalides,
)

__all__ = [
    "AccesDejaConfigure",
    "AccesNonConfigure",
    "ApplicationError",
    "ArcherDejaSorti",
    "ArcherEngage",
    "ArcherHorsBigShootOff",
    "ArcherIntrouvable",
    "ArretIntrouvable",
    "AucunDuelALancer",
    "BarrageIntrouvable",
    "BarragePerime",
    "BlasonHorsTournoi",
    "BlasonIntrouvable",
    "BlasonReference",
    "BriqueDejaEnBibliotheque",
    "BriqueHorsBibliotheque",
    "CategorieHorsTournoi",
    "CategorieIntrouvable",
    "ChangementCategorieArcherEngage",
    "ClubIntrouvable",
    "ClubReference",
    "CodePosteInconnu",
    "CodeScoreurInconnu",
    "DejaInscrit",
    "DepartAvecInscriptions",
    "DepartComplet",
    "DepartCourantNonDefini",
    "DepartEnCoursNonConfirme",
    "DepartIntrouvable",
    "DeplacementInvalide",
    "DernierDepartNonSupprimable",
    "DerouleCyclique",
    "DuelDesynchronise",
    "EffectifInsuffisantPourDemarrer",
    "EffectifSimulationInvalide",
    "EgaliteNonDepartageable",
    "ForfaitDejaDeclare",
    "ForfaitIntrouvable",
    "ForfaitTournoiTermine",
    "FormatIntrouvable",
    "FormatNonSimulable",
    "FusionArchersEngages",
    "FusionImpossible",
    "GabaritDuTournoiAbsent",
    "GabaritIntrouvable",
    "HomonymeArcher",
    "IdentifiantsInvalides",
    "InscriptionIntrouvable",
    "InscriptionPayeeARembourser",
    "MancheIntrouvable",
    "NomBriqueDejaPris",
    "NomClubDejaPris",
    "NomFormatDejaPris",
    "NonAuthentifie",
    "PeuplementTournoiDemarre",
    "PhaseEnPause",
    "PhaseIntrouvable",
    "PhasePasDesPoules",
    "PhasePasReglee",
    "PhasePasUnBigShootOff",
    "PhasePasUnSuisse",
    "PhasePasUnTableau",
    "PhasePasUneQualification",
    "PhaseQualificationAbsente",
    "PhaseQualificationNonSupprimable",
    "PhaseSourceReferencee",
    "PhasesEngagees",
    "PilotageSimulationInvalide",
    "PosteIntrouvable",
    "PosteNEstPasUnEcran",
    "PrelevementEnAttente",
    "RattachementTournoiTermine",
    "RemboursementDejaTraite",
    "RemboursementIntrouvable",
    "RencontreIntrouvable",
    "ReordonnancementPhasesInvalide",
    "ReplacementNonConfirme",
    "SaisieHorsCible",
    "ScenarioInconnu",
    "ScoreurHorsTournoi",
    "ScoreurIntrouvable",
    "SessionSimulationIntrouvable",
    "SimulationTournoiDemarre",
    "TireursDesignesInvalides",
    "TournoiArchiveNonModifiable",
    "TournoiEnCoursNonSupprimable",
    "TournoiIntrouvable",
    "TournoiSansDepart",
    "TournoiSansPhase",
    "TransitionStatutInvalide",
    "UniteSimulationInvalide",
]
