"""Erreurs du domaine (ADR-0007) — une règle métier est violée.

Racine `DomainError` : le domaine **ignore HTTP**. La traduction en réponse (HTTP 422,
code métier) se fait uniquement à la frontière API (`api/erreurs.py`).

**Paquet depuis l'action 2 de l'audit de maintenabilité** (03/08/2026) : les 94 classes vivaient
dans un **fichier unique de 941 lignes**, qu'il fallait ouvrir à presque chaque US — l'audit l'a
mesuré parmi les onze « passages obligés » du dépôt. Elles sont réparties par **thème métier**
(`referentiel`, `moteur`, `tir`, `exploitation`) et ce module les **ré-exporte toutes** : aucun
import existant n'a changé, aucune ligne de classe n'a bougé d'un caractère.

Une erreur neuve se pose désormais **dans son thème**, pas au milieu de quatre-vingts autres. Le
seul point commun restant est ce barillet — une ligne à y ajouter, contre trois cents lignes à
parcourir avant.
"""

from __future__ import annotations

from domain.erreurs.base import DomainError
from domain.erreurs.exploitation import (
    AuteurAuditInvalide,
    CadenceEcranInvalide,
    CodePosteInvalide,
    CodeScoreurInvalide,
    ConsigneEcranInvalide,
    DureePriseDeControleInvalide,
    HorodatageAuditInvalide,
    LibelleEcranInvalide,
    NomScoreurInvalide,
    ObjetAuditInvalide,
    PosteSansCible,
    PosteSansEcran,
    RemboursementMontantInvalide,
    SequenceVuesVide,
)
from domain.erreurs.moteur import (
    ArretProgrammeInvalide,
    CadenceValidationSuperieureAuBareme,
    ChocDePoulePossible,
    EffectifIncompatible,
    EffectifMinimumIncoherent,
    EffectifPhaseInvalide,
    EffectifTableauInvalide,
    ExigenceEffectifInvalide,
    FormatTableauIncoherent,
    GrainIncompatibleAvecTypePhase,
    MatchIntrouvable,
    MatchNonJouable,
    NombreVoleesParValidationInvalide,
    NombreVoleesParValidationManquant,
    PhaseQualificationIncomplete,
    PhaseSansClassementPrelevee,
    PhaseSansParticipant,
    PhaseSansSource,
    PlageInvalide,
    PlageSourceVide,
    PolitiqueInconnue,
    PolitiqueMalFormee,
    PrelevementVide,
    ProfondeurInvalide,
    RangSourceInvalide,
    RangsSourceInexistants,
    ReglageDePoulesInvalide,
    RoutingNonSupporte,
    SequenceOrdreInvalide,
    SerpentApresDesPoules,
    SeuilDeBarrageInvalide,
    SourceApresPhase,
    SourceIntrouvable,
    SourceMalFormee,
    SourcesQuiSeRecoupent,
    VainqueurHorsMatch,
)
from domain.erreurs.referentiel import (
    CapaciteBlasonInvalide,
    CapaciteCibleInvalide,
    CibleInvalide,
    FormatSansDepart,
    FormatSansEtape,
    HandicapInvalide,
    HauteurCentreInvalide,
    HoraireDepartInvalide,
    LibelleCategorieInvalide,
    NomArcherInvalide,
    NomBlasonInvalide,
    NombreCiblesInvalide,
    NombreFlechesParVoleeInvalide,
    NombreVoleesInvalide,
    NomClubInvalide,
    NomFormatInvalide,
    NomGabaritInvalide,
    NomTournoiInvalide,
    NumeroDepartInvalide,
    PhasesDeDepartsMeles,
    PrenomArcherInvalide,
    QuotaDepartInvalide,
    TailleBlasonInvalide,
    TarifDepartInvalide,
    ZonesBlasonInvalides,
)
from domain.erreurs.tir import (
    AppariementImpossible,
    BaremeDuelInvalide,
    BarrageIndecis,
    BarrageNonRequis,
    BarrageRequisAvantQualification,
    ConfigurationBarrageInvalide,
    ConfigurationBigShootOffInvalide,
    ConfigurationCollineInvalide,
    ConfigurationPouleInvalide,
    ConfigurationSuisseInvalide,
    DeclarantForfaitInvalide,
    DecoupageEnToursInvalide,
    DuelDejaTranche,
    DuelIncomplet,
    DuelVerrouille,
    HorodatageForfaitInvalide,
    NombreFlechesVoleeInvalide,
    NomIntervenantInvalide,
    NumeroMancheInvalide,
    NumeroVoleeInvalide,
    RienAValider,
    ScoreDeMancheManquant,
    ScoreInvalide,
    SerieIncomplete,
    ValeurHorsBlason,
    VoleeIntrouvable,
    VoleeNonVerrouillee,
    VoleeVerrouillee,
)

__all__ = [
    "AppariementImpossible",
    "ArretProgrammeInvalide",
    "AuteurAuditInvalide",
    "BaremeDuelInvalide",
    "BarrageIndecis",
    "BarrageNonRequis",
    "BarrageRequisAvantQualification",
    "CadenceEcranInvalide",
    "CadenceValidationSuperieureAuBareme",
    "CapaciteBlasonInvalide",
    "CapaciteCibleInvalide",
    "ChocDePoulePossible",
    "CibleInvalide",
    "CodePosteInvalide",
    "CodeScoreurInvalide",
    "ConfigurationBarrageInvalide",
    "ConfigurationBigShootOffInvalide",
    "ConfigurationCollineInvalide",
    "ConfigurationPouleInvalide",
    "ConfigurationSuisseInvalide",
    "ConsigneEcranInvalide",
    "DeclarantForfaitInvalide",
    "DecoupageEnToursInvalide",
    "DomainError",
    "DuelDejaTranche",
    "DuelIncomplet",
    "DuelVerrouille",
    "DureePriseDeControleInvalide",
    "EffectifIncompatible",
    "EffectifMinimumIncoherent",
    "EffectifPhaseInvalide",
    "EffectifTableauInvalide",
    "ExigenceEffectifInvalide",
    "FormatSansDepart",
    "FormatSansEtape",
    "FormatTableauIncoherent",
    "GrainIncompatibleAvecTypePhase",
    "HandicapInvalide",
    "HauteurCentreInvalide",
    "HoraireDepartInvalide",
    "HorodatageAuditInvalide",
    "HorodatageForfaitInvalide",
    "LibelleCategorieInvalide",
    "LibelleEcranInvalide",
    "MatchIntrouvable",
    "MatchNonJouable",
    "NomArcherInvalide",
    "NomBlasonInvalide",
    "NomClubInvalide",
    "NomFormatInvalide",
    "NomGabaritInvalide",
    "NomIntervenantInvalide",
    "NomScoreurInvalide",
    "NomTournoiInvalide",
    "NombreCiblesInvalide",
    "NombreFlechesParVoleeInvalide",
    "NombreFlechesVoleeInvalide",
    "NombreVoleesInvalide",
    "NombreVoleesParValidationInvalide",
    "NombreVoleesParValidationManquant",
    "NumeroDepartInvalide",
    "NumeroMancheInvalide",
    "NumeroVoleeInvalide",
    "ObjetAuditInvalide",
    "PhaseQualificationIncomplete",
    "PhaseSansClassementPrelevee",
    "PhaseSansParticipant",
    "PhaseSansSource",
    "PhasesDeDepartsMeles",
    "PlageInvalide",
    "PlageSourceVide",
    "PolitiqueInconnue",
    "PolitiqueMalFormee",
    "PosteSansCible",
    "PosteSansEcran",
    "PrelevementVide",
    "PrenomArcherInvalide",
    "ProfondeurInvalide",
    "QuotaDepartInvalide",
    "RangSourceInvalide",
    "RangsSourceInexistants",
    "ReglageDePoulesInvalide",
    "RemboursementMontantInvalide",
    "RienAValider",
    "RoutingNonSupporte",
    "ScoreDeMancheManquant",
    "ScoreInvalide",
    "SequenceOrdreInvalide",
    "SequenceVuesVide",
    "SerieIncomplete",
    "SerpentApresDesPoules",
    "SeuilDeBarrageInvalide",
    "SourceApresPhase",
    "SourceIntrouvable",
    "SourceMalFormee",
    "SourcesQuiSeRecoupent",
    "TailleBlasonInvalide",
    "TarifDepartInvalide",
    "VainqueurHorsMatch",
    "ValeurHorsBlason",
    "VoleeIntrouvable",
    "VoleeNonVerrouillee",
    "VoleeVerrouillee",
    "ZonesBlasonInvalides",
]
