"""Adapters de persistance SQLite (guide §7, ADR-0005).

Accès **synchrones** (SQLAlchemy sync), base en **mode WAL**, migrations Alembic.
Le domaine ignore tout de SQLAlchemy : ces adapters vivent dans l'infrastructure,
derrière les ports repository (`domain.ports`), dont `TournoiRepositorySQL` est la
première implémentation (E00US009).
"""

from infrastructure.db.base import Base
from infrastructure.db.config import DEFAULT_DATABASE_URL, default_database_url
from infrastructure.db.engine import Database, create_database_engine
from infrastructure.db.models import (
    ArcherORM,
    BarrageORM,
    BarrageTirORM,
    BlasonORM,
    CategorieORM,
    ClubORM,
    DepartORM,
    DerouleEtapeORM,
    DuelORM,
    EntreeAuditORM,
    ForfaitORM,
    FormatTournoiORM,
    GabaritSalleORM,
    InscriptionORM,
    PhaseORM,
    PlacementORM,
    PosteORM,
    ScoreORM,
    ScoreurORM,
    SerieORM,
    TournoiORM,
    VoleeORM,
)
from infrastructure.db.repositories import (
    ArcherRepositorySQL,
    AuditRepositorySQL,
    BarrageRepositorySQL,
    BlasonRepositorySQL,
    CategorieRepositorySQL,
    ClubRepositorySQL,
    DepartRepositorySQL,
    DerouleEtapeRepositorySQL,
    DuelRepositorySQL,
    ForfaitRepositorySQL,
    FormatTournoiRepositorySQL,
    GabaritSalleRepositorySQL,
    InscriptionRepositorySQL,
    PhaseRepositorySQL,
    PlacementRepositorySQL,
    PlacementTableauRepositorySQL,
    PosteRepositorySQL,
    RemboursementRepositorySQL,
    ScoreRepositorySQL,
    ScoreurRepositorySQL,
    SerieRepositorySQL,
    TournoiRepositorySQL,
)
from infrastructure.db.write_queue import (
    PostCommitListener,
    WriteCommand,
    WriteQueue,
    WriteQueueClosedError,
)

__all__ = [
    "DEFAULT_DATABASE_URL",
    "ArcherORM",
    "ArcherRepositorySQL",
    "AuditRepositorySQL",
    "BarrageORM",
    "BarrageRepositorySQL",
    "BarrageTirORM",
    "Base",
    "BlasonORM",
    "BlasonRepositorySQL",
    "CategorieORM",
    "CategorieRepositorySQL",
    "ClubORM",
    "ClubRepositorySQL",
    "Database",
    "DepartORM",
    "DepartRepositorySQL",
    "DerouleEtapeORM",
    "DerouleEtapeRepositorySQL",
    "DuelORM",
    "DuelRepositorySQL",
    "EntreeAuditORM",
    "ForfaitORM",
    "ForfaitRepositorySQL",
    "FormatTournoiORM",
    "FormatTournoiRepositorySQL",
    "GabaritSalleORM",
    "GabaritSalleRepositorySQL",
    "InscriptionORM",
    "InscriptionRepositorySQL",
    "PhaseORM",
    "PhaseRepositorySQL",
    "PlacementORM",
    "PlacementRepositorySQL",
    "PlacementTableauRepositorySQL",
    "PostCommitListener",
    "PosteORM",
    "PosteRepositorySQL",
    "RemboursementRepositorySQL",
    "ScoreORM",
    "ScoreRepositorySQL",
    "ScoreurORM",
    "ScoreurRepositorySQL",
    "SerieORM",
    "SerieRepositorySQL",
    "TournoiORM",
    "TournoiRepositorySQL",
    "VoleeORM",
    "WriteCommand",
    "WriteQueue",
    "WriteQueueClosedError",
    "create_database_engine",
    "default_database_url",
]
